compile:
	g++ -Iinclude -Iinclude/sdl -Iinclude/headers -Llib -o JumpKing src/*.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_image

run:
	g++ -Iinclude -Iinclude/sdl -Iinclude/headers -Llib -o JumpKing src/*.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_image
	./JumpKing.exe

run-only:
	./JumpKing.exe